version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  wf-api:
    container_name: wf-api 
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      - API_PORT=${PORT:-3000}
      - API_HOSTNAME=${HOSTNAME:-localhost}
    networks:
      - wf-network
    ports:
      - ${PORT:-3000}:3000
    healthcheck:
      test: curl localhost:${PORT:-3000}/api/health | grep 'Project Wayfinder API is healthy and ready'
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s

  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  wf-app:
    container_name: wf-app
    build:
      context: ./src/frontend-pwa
      dockerfile: Dockerfile
    networks:
      - wf-network
    ports: 
      - "5173:5173"
    healthcheck:
      test: curl --fail http://localhost:5173 || exit 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      wf-api:
        condition: service_healthy

networks:
  wf-network:
    driver: "bridge"
