version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  wf-api:
    container_name: wf-api 
    build:
      context: ./src/api
      dockerfile: Dockerfile
    networks:
      - wf-network
    ports:
      - "3004:3004"

networks:
  wf-network:
    driver: "bridge"