version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  wf-api:
    container_name: wf-api 
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-3000}
      - HOSTNAME=${HOSTNAME:-localhost}
    networks:
      - wf-network
    ports:
      - ${PORT:-3000}:3000
    healthcheck:
      test: curl localhost:${PORT:-3000}/api/health | grep 'Project Wayfinder API is healthy and ready'
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s

  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  wf-app:
    container_name: wf-app
    build:
      context: ./src/frontend-pwa
      dockerfile: Dockerfile
    networks:
      - wf-network
    ports: 
      - "5173:5173"
    healthcheck:
      test: curl --fail http://localhost:5173 || exit 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      wf-api:
        condition: service_healthy

  #############################################################################################
  ###                                       Mongo                                           ###
  #############################################################################################
  mongo:
    image: mongo:3.6
    container_name: mongodb
    tty: true
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE:-wf-db}
    volumes:
      - ./mongoSeed/init:/docker-entrypoint-initdb.d
      - ./mongo/init/data:/tmp/data 
      - ./mongo/data:/data/db 
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    networks:
      - wf-network
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u ${MONGO_USERNAME} -p ${MONGO_PASSWORD} --quiet | grep 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 120s

#############################################################################################
###                                       Network                                         ###
#############################################################################################

networks:
  wf-network:
    driver: "bridge"
