kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APPLICATION_NAME}-template
labels:
  template: ${APPLICATION_NAME}-template
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    annotations:
    app.openshift.io/connects-to: >-
        [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"wf-app-1-gn5nq"}]
      openshift.io/generated-by: OpenShiftWebConsole
    name: wf-app-1-gn5nq
    namespace: ec1236-dev
    labels:
      app: wf-app
      deployment: wf-app-1
      deploymentconfig: wf-app
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        containers:
          - resources:
              limits:
                cpu: 250m
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 256Mi
            terminationMessagePath: /dev/termination-log
            name: wf-app
            securityContext:
              capabilities:
                drop:
                  - ALL
              runAsUser: 1013750000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
            ports:
              - containerPort: 80
                protocol: TCP
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: kube-api-access-zvm2r
                readOnly: true
                mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            terminationMessagePolicy: File
            image: >-
              image-registry.openshift-image-registry.svc:5000/ec1236-dev/wf-app@sha256:4c5958ae0f91bf3fa906358eaad0ea760f2b2431a8aab483b48dc4ec5338231b
        serviceAccount: default
        dnsPolicy: ClusterFirst