---
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas: 
    SingleLocation:
      type: object
      properties:
        External_Site:
          type: string
          description: Service Offered - City
        Address:
          type: string
          description: Location of the office
        Locality:
          type: string
          description: Locale the office resides in
        Site_Phone_Number:
          type: string
          description: Site phone number
        Site_Fax_no:
          type: string
          description: Site fax number
        Website_URL:
          type: string
          description: Website for for the designated office
        Site_Email:
          type: string
          description: Email For the Site
        Latitude:
          type: float
          description: Latitude of the office address
        Longtitude:
          type: float
          description: Longtitude of the office address
        Office_Code:
          type: string
          description: Office Code
  securitySchemes: {}
info:
  title: Project Wayfinder API
  version: 1.0.0
  description: API for project Wayfinder
  license:
    name: ISC
  contact: {}
openapi: 3.0.0
paths:
  "/health":
    get:
      operationId: HealthCheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
              examples:
                Example 1:
                  value: Project Wayfinder API is happy and healthy
      description: Project Wayfinder's health handler to confirm API container is healthy
        and ready
      summary: Health endpoint for OpenShift
      tags:
      - Health
      security: []
      parameters: []
  "/locations":
    get:
      operationId: GetAllLocations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              type: array
              items:
                $ref: '#/components/schemas/SingleLocation'
                type:
                  object
              examples:
                Example 1:
                  value:
                    External_Site: 'Service BC - City'
                    Address: '740 Street st'
                    Locality: 'Vernon'
                    Site_Phone_No: '123 456-7890'
                    Site_Fax_no: '123 456-7890'
                    Website_URL: 'http://google.ca'
                    Site_Email: ''
                    Latitude: 50.265568
                    Longitude: -119.270538
                    Office_Code: '00093'
      description: Fetches all Locations in database for caching
      summary: Get Information for Locations
      tags:
      - Locations
      security: []
      parameters: []
      
servers:
- url: "/api"
