---
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas: {}
  securitySchemes: {}
info:
  title: Project Wayfinder API
  version: 1.0.0
  description: API for project Wayfinder
  license:
    name: ISC
  contact: {}
openapi: 3.0.0
paths:
  "/health":
    get:
      operationId: HealthCheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
              examples:
                Example 1:
                  value: Project Wayfinder API is happy and healthy
      description: Project Wayfinder's health handler to confirm API container is healthy
        and ready
      summary: Health endpoint for OpenShift
      tags:
      - Health
      security: []
      parameters: []
servers:
- url: "/api"